version: "3"
services:
  api:
   build: ./
   image: dalongrong/demo-ngx-vts
   ports:
   - "8080:80"
  g:
    image: grafana/grafana
    ports:
    - "3000:3000"
  p:
    image: prom/prometheus
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"